### PR TITLE
Disable configuration caching on CreateFocusSettingsTask

### PR DESCRIPTION
**Pull request by ZacSweers**
Partially handles #2 but doesn't implement actual support for configuration caching. This instead marks this task as incompatible with it, allowing Gradle to gracefully fall back to regular mode when this task runs rather than require users to manually disable CC first.

Gradle 7.5 will introduce APIs for depending on the resolved dependency graph in a CC-friendly way, but that's not ready yet. Example of that can be found here though: https://github.com/adammurdoch/dependency-graph-as-task-inputs/blob/main/plugins/src/main/java/TestPlugin.java#L31-L35

Note this also raises the minimum Gradle version to 7.4 unless you want to dynamically gate the API call at runtime on the gradle version

### CODE REVIEW

**Comment by ZacSweers** [comment]
The CLA link leads me to an inactionable screen (I can't appear to click anything or input anything?)

image

**Comment by digitalbuddha** [comment]
Weird, seems to be loading fine for me. Try again?

**Comment by ZacSweers** [comment]
Worked on mobile 👍

**Review by digitalbuddha — APPROVED** [review]

**Comment by digitalbuddha** [comment]
Raising apis seems fine, if we run into problems internally I’ll follow up and gate

**Comment by digitalbuddha** [comment]
Thanks Zac!

**Comment by eleventigerssc** [comment]
@digitalbuddha @ZacSweers it would be great if you could gate this call for Gradle versions below 7 for the poor folks who haven't got to the latest yet.

**Comment by ZacSweers** [comment]
I think that you should just update. I know the Gradle ecosystem has a long track record of supporting old versions for long periods of time, and I think that's significantly held back the Gradle ecosystem's evolution. If you care enough about your build QoL to adopt a tool like this, you should care enough to update it regularly IMO

**Comment by liutikas** [comment]
+1 Zac, configuration caching and project isolation compatibility is simply not something that will be possible to adopt by plugins without ugly hacks. Let's keep this modern!

**Pull request merged**
